### ISSUE TITLE
Invalid macro name `PXTextFloatIsAllowedCháracter`.

### ISSUE THREAD

**Issue by olafmersmann** [BitPaw/PXUltima#4]
[`PXTextFloatIsAllowedCháracter`](https://github.com/BitPaw/PXUltima/blob/ce9d57f49b7727bb472e4678b8490833ecfa99ef/Code/PXUltima/Source/Media/PXText.h#L16) isn't a valid macro name (should be a valid identifier).

**Comment by BitPaw** [comment]
Invalid name created by accidentally hitting Apostrofe (´) while typing.
MSVC and gcc compiler did not refuse compiling non standard name.

Changed in file Media/PXText.h on Apr 21, 2023
